name: Generate Cypress report
on:
  push:
    branches:
    - main

jobs:
  cypress-test:
    name: Run on Chrome 105
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Install cypress and verify
      run: 
        npm ci
        $(npm bin)/cypress verify
        
    - name: Run Cypress tests
      run: npm run test:chrome
      continue-on-error: false
      
    - name: Copy tests execution videos and screenshots
      run: 
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots
    
    - name: Merge tests reports
      run: npm run combine:report
      
    - name: Generate HTML report
      run: npm run generate:report 
          
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: $({ secret.GITHUB_TOKEN })
        publish_dir: ./public

